# Generated by Django 4.2.20 on 2025-04-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='responded',
            field=models.BooleanField(default=False),
        ),
    ]
